### PR TITLE
fix: respect `options.cwd` when running formatter

### LINKED ISSUE #130: 🐛 Bug: Consider respecting `options.cwd` to run formatter in
### Bug Report Checklist

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have pulled the latest `main` branch of the repository.
- [x] I have [searched for related issues](https://github.com/JoshuaKGoldberg/formatly/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Would you be open to use `cwd: options.cwd ?? process.cwd()` to run the formatter process in? Next to resolving the local formatter using `options.cwd`, shouldn't we also run it from there?

### Actual

When spawning the process we're using `cwd: process.cwd()`:

https://github.com/JoshuaKGoldberg/formatly/blob/4f79035ba8ba74fc66eb8e255c8670da0895bf4e/src/formatly.ts#L59

### Additional Info

This is generally not an issue. But in a test from a fixture folder I noticed it ran from `process.cwd()`, formatting the whole project—not just the fixture folder containing the config file (there's a `biome.json` in both root and fixture folder).

### PR DESCRIPTION
**Pull request by webpro**
## PR Checklist

- [x] Addresses an existing open issue: fixes #130
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/formatly/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/formatly/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Respect `options.cwd` when spawning the formatter process, and fall back to `process.cwd()` if it isn't set.

### CODE REVIEW

File: src/formatly.ts [hunk 1]
```diff
@@ -56,7 +56,7 @@ export async function formatly(
 		ran: true,
 		result: await new Promise((resolve, reject) => {
 			const child = spawn(baseCommand, [...args, ...patterns], {
-				cwd: process.cwd(),
+				cwd: options.cwd ?? process.cwd(),
```
Comment (JoshuaKGoldberg) [inline src/formatly.ts:59]: [Testing] It'd be nice to add unit tests to ensure the right cwd is used. Do you have time to add a couple to `formatly.test.ts`?

Comment (JoshuaKGoldberg) [inline src/formatly.ts:59]: [Refactor] `resolveFormatter` also has cwd defaulting logic:

https://github.com/JoshuaKGoldberg/formatly/blob/7b8cddbadc78b9fb1c6c0b353bac6679f95c1b98/src/resolveFormatter.ts#L6-L7

...which I think comes out to basically the same thing as `?? process.cwd()`. WDYT about, say, having a single cwd variable set in this function that's passed down later? As in, only having one place where cwd has a default set?

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, nice and straightforward - thanks!

Left a couple of comments but I don't think they need to block. I'm happy to do them if you don't have the time. Up to you 🙂 - let me know?

File: src/formatly.ts (hunk 1 above)
Comment (webpro) [reply src/formatly.ts]: Sure! Added one test to `formatly.test.ts`.

And a new "integration" test file as well as I think it makes sense to have a "clean" but complete test for detecting the formatter inside a custom `options.cwd` and then spawning the right process based on that. A new file, because for this test `mockResolveFormatter` must not be mocked. Happy to cut down to test to fit it into `resolveFormatter.test.ts`, though. Just let me know what makes sense to you, I'd fully understand the idea to stick to having unit tests only.

Comment (webpro) [reply src/formatly.ts]: Done, but this means the only argument to `resolveFormatter` is no longer optional.

Comment (JoshuaKGoldberg) [reply src/formatly.ts]: Oh, hmm, you're right. Darn. Having `resolveFormatter`'s argument be optional is really nice for end-users of it... I guess we'll just have to live with the duplicate defaulting. I'll switch it back - sorry for the back-and-forht.

Comment (JoshuaKGoldberg) [reply src/formatly.ts]: Yeah, I normally don't personally go for integration tests - but also haven't worked on a project quite like formatly before (cwd sensitivity, shell scripts, etc.). I think this makes sense to try out. Let's go for it! 🥳 

Also filed #142 for end-to-end tests if you're interested.

**Review by JoshuaKGoldberg — APPROVED** [review]
Thanks, this looks great - much appreciated! 🙌

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @webpro for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Comment by webpro** [comment]
Thanks for merging this, Josh!
